##  -*- python -*-  
# db file automatically generated by genconf on: Tue Sep 23 15:09:20 2008
## insulates outside world against anything bad that could happen
## also prevents global scope pollution
def _fillCfgDb():
    from GaudiKernel.Proxy.ConfigurableDb import CfgDb

    # get a handle on the repository of Configurables
    cfgDb = CfgDb()

    # populate the repository with informations on Configurables 

    cfgDb.add( configurable = 'LoKi__ODINFilter',
               package = 'LoKiHlt',
               module  = 'LoKiHlt.LoKiHltConf',
               lib     = 'LoKiHlt' )
    cfgDb.add( configurable = 'LoKi__L0Filter',
               package = 'LoKiHlt',
               module  = 'LoKiHlt.LoKiHltConf',
               lib     = 'LoKiHlt' )
    cfgDb.add( configurable = 'LoKi__Hybrid__HltFactory',
               package = 'LoKiHlt',
               module  = 'LoKiHlt.LoKiHltConf',
               lib     = 'LoKiHlt' )
    cfgDb.add( configurable = 'LoKi__HDRFilter',
               package = 'LoKiHlt',
               module  = 'LoKiHlt.LoKiHltConf',
               lib     = 'LoKiHlt' )
    return #_fillCfgDb
# fill cfgDb at module import...
try:
    _fillCfgDb()
    #house cleaning...
    del _fillCfgDb
except Exception,err:
    print "Py:ConfigurableDb   ERROR Problem with [%s] content!" % __name__
    print "Py:ConfigurableDb   ERROR",err
    print "Py:ConfigurableDb   ERROR   ==> culprit is package [LoKiHlt] !"
